---
- name: Deploy
  hosts: all
  become: true

  tasks:

    - name: Pull Image
      community.docker.docker_image:
        name: "prashantkumar1911/pkdev-tata"
        tag: "latest"
        source: pull

    - name: Start Container
      community.docker.docker_container:
        name: pkdev-tata
        image: "prashantkumar1911/pkdev-tata:latest"
        state: started
        recreate: true
        pull: true
        restart_policy: always
        published_ports:
          - "8080:8080"

    - name: Remove dangling Docker images
      command: docker image prune -af


