name: PKDEV_TATA_Pipeline

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Java 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make maven wrapper executable
        run: chmod +x mvnw

      - name: Build Maven
        run: |
          ./mvnw clean package

      - name: Verify Target
        run: |
          ls -lh target

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: pkdev-tata-project
          path: target/*.jar

      - name: Build Docker Image
        run: |
          docker build  \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/pkdev-tata:${{ github.sha }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/pkdev-tata:latest \
            .
          
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker Image to DockerHub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pkdev-tata:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pkdev-tata:latest
          

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull New Image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pkdev-tata:${{ github.sha }}

      - name: Restart Container
        run: |
          docker rm -f pkdev-tata || true          
          docker run -d \
            --name pkdev-tata \
            --restart unless-stopped \
            -p 8080:8080 \
            ${{ secrets.DOCKERHUB_USERNAME }}/pkdev-tata:${{ github.sha }}

      - name: Verify Container
        run: |
          docker ps

      - name: Verify Application
        run: |
          sleep 20
          curl --fail http://localhost:8080

      - name: Remove Unused Images
        run: |
          docker image prune -af

      - name: Show Container Logs
        if: failure()
        run: |
          docker logs pkdev-tata